pre-release-commit-message = "release: project-origins v{{version}}"
tag-prefix = "project-origins-"
tag-message = "project-origins {{version}}"

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "^## Next.*$"
replace = "## Next (YYYY-MM-DD)\n\n## v{{version}} ({{date}})"
prerelease = true
max = 1
