# Dependabot dependency version checks / updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/lib"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/events"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/signals"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/supervisor"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/filterer/ignore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/filterer/globset"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/bosion"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/ignore-files"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/crates/project-origins"
    schedule:
      interval: "weekly"
