status = ["Merge test on %"]
use_squash_merge = true
delete_merged_branches = true
update_base_for_deletes = true

# Disabled until https://github.com/bors-ng/bors-ng/issues/1434 is fixed
#pr_status = ["PR check on ubuntu"]
