delete_merged_branches = true
update_base_for_deletes = true

# needs to remain squash for current release process
use_squash_merge = true

status = [
	"Test on macos with Rust stable",
	"Test on ubuntu with Rust stable",
	"Test on windows with Rust stable",
	"Test on macos with Rust 1.58.0",
	"Test on ubuntu with Rust 1.58.0",
	"Test on windows with Rust 1.58.0",
]

# Disabled until https://github.com/bors-ng/bors-ng/issues/1434 is fixed
#pr_status = [
#	"Check on macos",
#	"Check on ubuntu",
#	"Check on windows",
#]
