pre-release-hook = ["../../../bin/pre-release-pull"]
pre-release-commit-message = "tagged filterer: v{{version}}"
tag-prefix = "filterer-tagged-"
tag-message = "watchexec-filterer-tagged {{version}}"
