name: Manpage and completions up to date

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

env:
  CARGO_TERM_COLOR: always
  CARGO_UNSTABLE_SPARSE_REGISTRY: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  manpage:
    name: Check manpage is up to date
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure toolchain
      run: |
        rustup toolchain install stable --profile minimal --no-self-update --component clippy
        rustup default stable

    - run: bin/manpage
    - run: git diff --exit-code -- doc/wachexec.1
